### ISSUE TITLE
Gather inspiration resources and put links into readme.md

### ISSUE THREAD

**Issue by mcelearr** [The-Hip-Hip-Arrays/blog#2]

**Comment by gabrielperales** [comment]
I like this 2 designs:
- [Dopetrope](https://html5up.net/dopetrope)
- [Arcana](https://html5up.net/arcana)

what do you prefer? /cc @The-Hip-Hip-Arrays/Team

**Comment by mcelearr** [comment]
I like Arcana the best. I say we base the look of the app on that. We can build our one from scratch and of course add our own twist!

**Comment by mcelearr** [comment]
Planning phase complete so this is no longer relevant
