### ISSUE TITLE
Project tecnologies

### ISSUE THREAD

**Issue by gabrielperales** [The-Hip-Hip-Arrays/blog#4]
Here we can discuss about what technologies we should use for this project

/cc @The-Hip-Hip-Arrays/team

**Comment by mcelearr** [comment]
It would be groovy to use SASS. Gabriel to lead on this and to share findings with the group.

**Comment by gabrielperales** [comment]
if we are going to use SASS... maybe we should use Gulp to compile SASS into CSS, and by the way, we can get a server with livereload for developing, this will allow us develop quickly.

**Comment by mcelearr** [comment]
Change of plan. We're not going to use SASS after all. Just vanilla CSS.

**Comment by gabrielperales** [comment]
Ok, I close this.
