### ISSUE TITLE
Could app.js be made more understandable?

### ISSUE THREAD

**Issue by helau64** [The-Hip-Hip-Arrays/blog#55]
The comments are great, and I know it's good to have succinct code, but I have absolutely no idea what's happening here.

**Comment by otajor** [comment]
I don't like that it looks very much like jQuery. But I do like that you've pretty much re-implemented jQuery yourself (@heatherlauren check out their micro.js file and have a look at what's going on there; app.js is just using functions from micro.js to make interacting with the DOM simpler).
